# Generated by Django 4.1.4 on 2023-01-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, editable=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult', to_field='task_id')),
            ],
        ),
    ]
